### ISSUE TITLE
AutoDrawer Not Opening

### ISSUE THREAD

**Issue by javon-projects** [Siydge/autodraw-roblox#3]
When I Tried Opening AutoDrawer it created a folder called %AppData% but it did not open

**Comment by AlexDalas** [comment]
Are you running v1.2 or v1.1b?

**Comment by AlexDalas** [comment]
Ah, I have made a mistake. The application was not meant to make a folder called %AppData%, but was meant to create a directory in your appdata folder. v1.2a fixes this issue.

[Download here](https://github.com/Siydge/autodraw-roblox/releases/tag/v1.2a)

**Comment by javon-projects** [comment]
> Are you running v1.2 or v1.1b?

v1.2

**Comment by AlexDalas** [comment]
Test out v1.2a and let me know what happens

**Comment by javon-projects** [comment]
Thank you, it's working now.

**Comment by javon-projects** [comment]
> Alright
